# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: questions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='questions.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fquestions.proto\"j\n\x08Question\x12\x13\n\x0bquestion_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x18\n\x10\x64ifficulty_level\x18\x03 \x01(\t\x12\x0e\n\x06is_MCQ\x18\x04 \x01(\x08\x12\r\n\x05grade\x18\x05 \x01(\x02\"\x11\n\x0fQuestionRequest\"0\n\x10QuestionResponse\x12\x1c\n\tquestions\x18\x01 \x03(\x0b\x32\t.Question\"*\n\x13QuestionByIdRequest\x12\x13\n\x0bquestion_id\x18\x01 \x01(\x05\"3\n\x14QuestionByIdResponse\x12\x1b\n\x08question\x18\x01 \x01(\x0b\x32\t.Question\"5\n\x16QuestionPostingRequest\x12\x1b\n\x08question\x18\x01 \x01(\x0b\x32\t.Question\"2\n\x17QuestionPostingResponse\x12\x17\n\x0fposting_message\x18\x01 \x01(\t\"<\n\x16QuestionEditingRequest\x12\x13\n\x0bquestion_id\x18\x01 \x01(\x05\x12\r\n\x05grade\x18\x02 \x01(\x02\"1\n\x17QuestionEditingResponse\x12\x16\n\x0eupdate_message\x18\x01 \x01(\t\",\n\x15QuestionDeleteRequest\x12\x13\n\x0bquestion_id\x18\x01 \x01(\x05\"0\n\x16QuestionDeleteResponse\x12\x16\n\x0e\x64\x65lete_message\x18\x01 \x01(\t2\xce\x02\n\tQuestions\x12\x36\n\x0fGetAllQuestions\x12\x10.QuestionRequest\x1a\x11.QuestionResponse\x12>\n\x0fGetQuestionById\x12\x14.QuestionByIdRequest\x1a\x15.QuestionByIdResponse\x12\x41\n\x0cPostQuestion\x12\x17.QuestionPostingRequest\x1a\x18.QuestionPostingResponse\x12\x43\n\x0eModifyQuestion\x12\x17.QuestionEditingRequest\x1a\x18.QuestionEditingResponse\x12\x41\n\x0e\x44\x65leteQuestion\x12\x16.QuestionDeleteRequest\x1a\x17.QuestionDeleteResponseb\x06proto3'
)




_QUESTION = _descriptor.Descriptor(
  name='Question',
  full_name='Question',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question_id', full_name='Question.question_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='Question.category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='difficulty_level', full_name='Question.difficulty_level', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_MCQ', full_name='Question.is_MCQ', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grade', full_name='Question.grade', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=125,
)


_QUESTIONREQUEST = _descriptor.Descriptor(
  name='QuestionRequest',
  full_name='QuestionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=144,
)


_QUESTIONRESPONSE = _descriptor.Descriptor(
  name='QuestionResponse',
  full_name='QuestionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='questions', full_name='QuestionResponse.questions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=194,
)


_QUESTIONBYIDREQUEST = _descriptor.Descriptor(
  name='QuestionByIdRequest',
  full_name='QuestionByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question_id', full_name='QuestionByIdRequest.question_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=238,
)


_QUESTIONBYIDRESPONSE = _descriptor.Descriptor(
  name='QuestionByIdResponse',
  full_name='QuestionByIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='QuestionByIdResponse.question', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=291,
)


_QUESTIONPOSTINGREQUEST = _descriptor.Descriptor(
  name='QuestionPostingRequest',
  full_name='QuestionPostingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='QuestionPostingRequest.question', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=346,
)


_QUESTIONPOSTINGRESPONSE = _descriptor.Descriptor(
  name='QuestionPostingResponse',
  full_name='QuestionPostingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='posting_message', full_name='QuestionPostingResponse.posting_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=398,
)


_QUESTIONEDITINGREQUEST = _descriptor.Descriptor(
  name='QuestionEditingRequest',
  full_name='QuestionEditingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question_id', full_name='QuestionEditingRequest.question_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grade', full_name='QuestionEditingRequest.grade', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=460,
)


_QUESTIONEDITINGRESPONSE = _descriptor.Descriptor(
  name='QuestionEditingResponse',
  full_name='QuestionEditingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='update_message', full_name='QuestionEditingResponse.update_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=511,
)


_QUESTIONDELETEREQUEST = _descriptor.Descriptor(
  name='QuestionDeleteRequest',
  full_name='QuestionDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question_id', full_name='QuestionDeleteRequest.question_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=557,
)


_QUESTIONDELETERESPONSE = _descriptor.Descriptor(
  name='QuestionDeleteResponse',
  full_name='QuestionDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='delete_message', full_name='QuestionDeleteResponse.delete_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=559,
  serialized_end=607,
)

_QUESTIONRESPONSE.fields_by_name['questions'].message_type = _QUESTION
_QUESTIONBYIDRESPONSE.fields_by_name['question'].message_type = _QUESTION
_QUESTIONPOSTINGREQUEST.fields_by_name['question'].message_type = _QUESTION
DESCRIPTOR.message_types_by_name['Question'] = _QUESTION
DESCRIPTOR.message_types_by_name['QuestionRequest'] = _QUESTIONREQUEST
DESCRIPTOR.message_types_by_name['QuestionResponse'] = _QUESTIONRESPONSE
DESCRIPTOR.message_types_by_name['QuestionByIdRequest'] = _QUESTIONBYIDREQUEST
DESCRIPTOR.message_types_by_name['QuestionByIdResponse'] = _QUESTIONBYIDRESPONSE
DESCRIPTOR.message_types_by_name['QuestionPostingRequest'] = _QUESTIONPOSTINGREQUEST
DESCRIPTOR.message_types_by_name['QuestionPostingResponse'] = _QUESTIONPOSTINGRESPONSE
DESCRIPTOR.message_types_by_name['QuestionEditingRequest'] = _QUESTIONEDITINGREQUEST
DESCRIPTOR.message_types_by_name['QuestionEditingResponse'] = _QUESTIONEDITINGRESPONSE
DESCRIPTOR.message_types_by_name['QuestionDeleteRequest'] = _QUESTIONDELETEREQUEST
DESCRIPTOR.message_types_by_name['QuestionDeleteResponse'] = _QUESTIONDELETERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Question = _reflection.GeneratedProtocolMessageType('Question', (_message.Message,), {
  'DESCRIPTOR' : _QUESTION,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:Question)
  })
_sym_db.RegisterMessage(Question)

QuestionRequest = _reflection.GeneratedProtocolMessageType('QuestionRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONREQUEST,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:QuestionRequest)
  })
_sym_db.RegisterMessage(QuestionRequest)

QuestionResponse = _reflection.GeneratedProtocolMessageType('QuestionResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONRESPONSE,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:QuestionResponse)
  })
_sym_db.RegisterMessage(QuestionResponse)

QuestionByIdRequest = _reflection.GeneratedProtocolMessageType('QuestionByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONBYIDREQUEST,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:QuestionByIdRequest)
  })
_sym_db.RegisterMessage(QuestionByIdRequest)

QuestionByIdResponse = _reflection.GeneratedProtocolMessageType('QuestionByIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONBYIDRESPONSE,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:QuestionByIdResponse)
  })
_sym_db.RegisterMessage(QuestionByIdResponse)

QuestionPostingRequest = _reflection.GeneratedProtocolMessageType('QuestionPostingRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONPOSTINGREQUEST,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:QuestionPostingRequest)
  })
_sym_db.RegisterMessage(QuestionPostingRequest)

QuestionPostingResponse = _reflection.GeneratedProtocolMessageType('QuestionPostingResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONPOSTINGRESPONSE,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:QuestionPostingResponse)
  })
_sym_db.RegisterMessage(QuestionPostingResponse)

QuestionEditingRequest = _reflection.GeneratedProtocolMessageType('QuestionEditingRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONEDITINGREQUEST,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:QuestionEditingRequest)
  })
_sym_db.RegisterMessage(QuestionEditingRequest)

QuestionEditingResponse = _reflection.GeneratedProtocolMessageType('QuestionEditingResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONEDITINGRESPONSE,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:QuestionEditingResponse)
  })
_sym_db.RegisterMessage(QuestionEditingResponse)

QuestionDeleteRequest = _reflection.GeneratedProtocolMessageType('QuestionDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONDELETEREQUEST,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:QuestionDeleteRequest)
  })
_sym_db.RegisterMessage(QuestionDeleteRequest)

QuestionDeleteResponse = _reflection.GeneratedProtocolMessageType('QuestionDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONDELETERESPONSE,
  '__module__' : 'questions_pb2'
  # @@protoc_insertion_point(class_scope:QuestionDeleteResponse)
  })
_sym_db.RegisterMessage(QuestionDeleteResponse)



_QUESTIONS = _descriptor.ServiceDescriptor(
  name='Questions',
  full_name='Questions',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=610,
  serialized_end=944,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllQuestions',
    full_name='Questions.GetAllQuestions',
    index=0,
    containing_service=None,
    input_type=_QUESTIONREQUEST,
    output_type=_QUESTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetQuestionById',
    full_name='Questions.GetQuestionById',
    index=1,
    containing_service=None,
    input_type=_QUESTIONBYIDREQUEST,
    output_type=_QUESTIONBYIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PostQuestion',
    full_name='Questions.PostQuestion',
    index=2,
    containing_service=None,
    input_type=_QUESTIONPOSTINGREQUEST,
    output_type=_QUESTIONPOSTINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ModifyQuestion',
    full_name='Questions.ModifyQuestion',
    index=3,
    containing_service=None,
    input_type=_QUESTIONEDITINGREQUEST,
    output_type=_QUESTIONEDITINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteQuestion',
    full_name='Questions.DeleteQuestion',
    index=4,
    containing_service=None,
    input_type=_QUESTIONDELETEREQUEST,
    output_type=_QUESTIONDELETERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUESTIONS)

DESCRIPTOR.services_by_name['Questions'] = _QUESTIONS

# @@protoc_insertion_point(module_scope)
